1.

In [1]:
s='sjogso'
type(s)

str

In [9]:
l=[1,2,3,4]
print(type(l),len(l))
s={'sf','sfs','sfsg'}
print(type(s),len(s))
dict={'name':'zyf','age':18}
print(type(dict),len(dict)) 
t='shigs',
print(type(t),len(t))
r=range(2,100,5)
print(type(r),len(r))
f=round(3.1415926,2 )
print(type(f),f)
b=True
print(type(b))
i=15
print(type(i))

<class 'list'> 4
<class 'set'> 3
<class 'dict'> 2
<class 'tuple'> 1
<class 'range'> 20
<class 'float'> 3.14
<class 'bool'>
<class 'int'>

In [13]:
# 类
class User:
    def __init__(self,name,age):
        self.name=name
        self.age=age
    
    def say(self):
        print(f'我是{self.name}，我今年{self.age}岁')
    
    def age_next_year(self):
        print(f'我明年{self.age+1}岁')


user1=User(name='zyf',age=18)
user1.say()
user1.age_next_year()

我是zyf，我今年18岁
我明年19岁

In [14]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## 认识numpy和pandas

1. numpy--arrray类，矩阵计算功能十分强大
2. pandas--DataFrame类，数据处理功能十分强大

In [15]:
import numpy as np
import pandas as pd

In [20]:
array1=np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [21]:
array1+3,array1*2

(array([4, 5, 6, 7, 8]), array([ 2,  4,  6,  8, 10]))

In [25]:
# 数组只能存放相同类型的数据，如果同时存放不同类型的的数据，会自动转换为相同类型的数组
array1=np.array([1,2,3,4,'hello'])
array1

array(['1', '2', '3', '4', 'hello'], dtype='<U21')

In [26]:
# 多维数组
array2=np.array([[1,2,3],[4,5,6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# 获取数组的形状和维度
array1.shape # (5,)
array1.ndim # 1
array2.shape # (2,3)
# array2.ndim  # 2

(2, 3)

In [31]:
# 生成等差数列的方法，arrange函数 arrange(start,stop,step)
a1=np.arange(10)
a2=np.arange(1,10)
a3=np.arange(1,10,2) 

a1,a2,a3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 3, 5, 7, 9]))

In [35]:
# 多种生成数组的方法
# np.tile函数
a1=np.tile(a1,2)
a2=np.tile(a2,(2,1))
a3=np.tile(a3,(2,1))
a1,a2,a3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[1, 3, 5, 7, 9],
        [1, 3, 5, 7, 9]]))

In [39]:
zeros=np.zeros((2,3))
ones=np.ones((2,3))
np.tile(0,3)
zeros,ones

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

In [42]:
# 数组的切片
a1[0:5]
a2[:,0:2]

array([[1, 2],
       [1, 2]])

In [61]:
# dataframe
l=['A','B','C','D','E','F','G','H','I','J']
df1=pd.DataFrame({'col1':range(10),'col2':l})
df1

   col1 col2
0     0    A
1     1    B
2     2    C
3     3    D
4     4    E
5     5    F
6     6    G
7     7    H
8     8    I
9     9    J

In [62]:
df2=pd.read_csv("../pystat-code-2021-01-25/2-4-1-sample_data.csv")
df2

   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C

In [66]:
# 纵向连接dataframe
df3=pd.concat([df1,df2],axis=0)
df3
# 横向连接dataframe
df4=pd.concat([df1,df2],axis=1)
df4

   col1 col2  col1 col2
0     0    A   1.0    A
1     1    B   2.0    A
2     2    C   3.0    B
3     3    D   4.0    B
4     4    E   5.0    C
5     5    F   6.0    C
6     6    G   NaN  NaN
7     7    H   NaN  NaN
8     8    I   NaN  NaN
9     9    J   NaN  NaN

In [70]:
df3['col2']
# 或者
df3.col2

df4[['col1','col2']]

   col1  col1 col2 col2
0     0   1.0    A    A
1     1   2.0    B    A
2     2   3.0    C    B
3     3   4.0    D    B
4     4   5.0    E    C
5     5   6.0    F    C
6     6   NaN    G  NaN
7     7   NaN    H  NaN
8     8   NaN    I  NaN
9     9   NaN    J  NaN

In [72]:
# 删除列
df4.drop(columns=['col2'],inplace=True)
df4

   col1  col1
0     0   1.0
1     1   2.0
2     2   3.0
3     3   4.0
4     4   5.0
5     5   6.0
6     6   NaN
7     7   NaN
8     8   NaN
9     9   NaN

In [82]:
# head()函数查看前n行
df3.head(3)
# tail()函数查看后n行
df3.tail(3)
df3

   col1 col2
0     0    A
1     1    B
2     2    C
3     3    D
4     4    E
5     5    F
6     6    G
7     7    H
8     8    I
9     9    J
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C

In [ ]:
# query()函数根据条件筛选数据,最后指定返回的列名
df3.query('col2=="B" | col2=="C"')['col1'] # &、|、~分别表示与、或、非操作

1    1
2    2
Name: col1, dtype: int64

In [93]:
type(df3),type(df3['col1'])
# s1=pd.Series(range(10))
# type(s1)
type(np.array(df3.col1))
# type(df3.col1.values) # numpy.ndarray

numpy.ndarray